language: bash
arch:
  - arm64

services:
  - docker

script:
  - docker build -t pestotoast/elasticsearch-armhf:${TRAVISTAG:-latest} .
  - echo "$DOCKER_PASSWORD" | docker login -u pestotoast --password-stdin
  - docker push pestotoast/elasticsearch-armhf:latest:${TRAVISTAG:-latest}
